#LINUX_OVERRIDE_SRCDIR=$(CONFIG_DIR)/../MA35D1_linux-5.4.y
#UBOOT_OVERRIDE_SRCDIR=$(CONFIG_DIR)/../MA35D1_u-boot-v2020.07
#ARM_TRUSTED_FIRMWARE_OVERRIDE_SRCDIR=$(CONFIG_DIR)/../MA35D1_arm-trusted-firmware-v2.3
ARM_TRUSTED_FIRMWARE_OVERRIDE_SRCDIR=$(CONFIG_DIR)/../arm-trusted-firmware-v2.3
#OPTEE_OS_SRCDIR=$(CONFIG_DIR)/../MA35D1_optee_os-v3.9.0

